---
title: N wands linked 2D tree
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{N wands linked 2D tree}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(treefit)
library(ggplot2)
library(gridExtra)
```

```{r}
for (n_wands_list in list(c(3, 3), c(3, 4), c(3, 5), c(3, 3, 3))) {
  all_estimated <- data.frame()
  for (fatness in c(0.1, 0.2, 0.3, 0.4, 0.5, 0.75)) {
    tree <-
      generate_n_wands_linked_2d_tree_expression(rep(200, length(n_wands_list)),
                                                 n_wands_list,
                                                 fatness)
    original_graph <-
      ggplot(as.data.frame(tree),
             aes(V1, V2)) +
      geom_point(size=0.1) +
      coord_cartesian(xlim=c(0, 6), ylim=c(-5, 1)) +
      labs(title=paste("N wands list:", paste(n_wands_list, collapse=", "), "\n",
                       "fatness:", fatness))
    perturbated_graph <-
      ggplot(as.data.frame(perturbate_knn(tree)),
             aes(V1, V2)) +
      geom_point(size=0.1) +
      coord_cartesian(xlim=c(0, 6), ylim=c(-5, 1)) +
      labs(title=paste("N wands list:", paste(n_wands_list, collapse=", "), "\n",
                       "fatness:", fatness,
                       "(perturbated)"))
    estimated <- estimate(list(expression=tree))
    estimated_graph <-
      plot_estimated(estimated) +
      labs(title=paste("N wands list:", paste(n_wands_list, collapse=", "),
                       "fatness:", fatness,
                       "(Grassman distance)"))
    all_estimated <-
      rbind(all_estimated,
            cbind(estimated,
                  fatness=fatness))
    plot(grid.arrange(original_graph, perturbated_graph,
                      estimated_graph,
                      layout_matrix=rbind(c(1, 2),
                                          c(3, 3))))
  }
  plot(plot_estimated(all_estimated) +
         facet_wrap(vars(fatness)) +
         labs(title=paste("N wands list:", paste(n_wands_list, collapse=", "),
                          "(Grassman distance for each K)")))
}
```
