title: Treefit for R
description: Treefit for R - Hayamizu lab
latest_version: 0.9.0
markdown: kramdown
highlighter: rouge
exclude:
  - ".dir-locals.el"
  - "Gemfile"
  - "Gemfile.lock"
  - "Rakefile"
  - "vendor"

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]

sass:
  sass_dir: assets/stylesheets
