name: Check
on:
  - push
  - pull_request
jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos
          - ubuntu
          - windows
        R:
          - "devel"
          - "4.0"
          - "3.6"
          - "3.5"
        exclude:
          - os: macos
            R: "devel"
          - os: macos
            R: "3.5"
          - os: ubuntu
            R: "devel"
          - os: windows
            R: "3.5"
    name: R ${{ matrix.R }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.R }}
      - name: Install system packages
        if: |
          matrix.os == 'ubuntu'
        run: |
          sudo apt update
          sudo apt install -V -y \
            libcurl4-openssl-dev \
            pandoc-citeproc \
            qpdf
      - name: Install remotes
        run: |
          Rscript -e "install.packages(c('remotes'))"
      - name: Install rcmdcheck
        run: |
          Rscript -e "remotes::install_cran(c('rcmdcheck'))"
      - name: Install BiocManager
        run: |
          Rscript -e "install.packages(c('BiocManager'))"
          Rscript -e "BiocManager::install()"
      - name: Install multtest separately
        run: |
          Rscript -e "BiocManager::install(c('multtest'))"
      - name: Install old caTools for R 3.5
        if: |
          matrix.R == '3.5'
        run: |
          Rscript -e "remotes::install_version('caTools', '1.17.1.4')"
      - name: Install old ROCR for R 3.5
        if: |
          matrix.R == '3.5'
        run: |
          Rscript -e "remotes::install_version('ROCR', '1.0-7')"
      - name: Install old Seurat for R 3.5 and 3.6
        if: |
          matrix.R == '3.5' || matrix.R == '3.6'
        run: |
          Rscript -e "remotes::install_version('Seurat', '< 4')"
      - name: Install dependencies
        run: |
          Rscript -e "remotes::install_deps(dependencies=TRUE)"
      - name: Check
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(args=c('--as-cran'), error_on='warning', check_dir='check')"
