name: Check
on:
  - push
  - pull_request
jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos
          - ubuntu
          - windows
        R:
          - "devel"
          - "3.6"
          - "3.5"
        exclude:
          - os: macos
            R: "3.5"
          - os: ubuntu
            R: "devel"
    name: R ${{ matrix.R }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.R }}
      - name: Install system packages
        if: |
          matrix.os == 'ubuntu'
        run: |
          sudo apt update
          sudo apt install -V -y \
            libcurl4-openssl-dev \
            pandoc-citeproc \
            qpdf
      - name: Install devtools
        run: |
          Rscript -e "install.packages(c('devtools'))"
      - name: Install BiocManager
        run: |
          Rscript -e "install.packages(c('BiocManager'))"
          Rscript -e "BiocManager::install()"
      - name: Install multtest separately
        run: |
          Rscript -e "BiocManager::install(c('multtest'))"
      - name: Install old caTools for R 3.5
        if: |
          matrix.R == '3.5'
        run: |
          Rscript -e "devtools::install_version('caTools', version='1.17.1.4')"
      - name: Install dependencies
        run: |
          Rscript -e "devtools::install_deps(dependencies=TRUE)"
      - name: Test
        run: |
          Rscript -e "devtools::test()"
      - name: Check
        run: |
          Rscript -e "devtools::check(cran=TRUE)"
